# Kang Data

## Import Packages

In [1]:
import scanpy as sc
import pandas as pd

## Load Data

In [2]:
# adata file
adata = sc.read_h5ad("../../data/kang/01-pro/Kang18.h5ad")
adata.X = adata.layers["logcounts"]
adata

AnnData object with n_obs × n_vars = 12516 × 4180
    obs: 'cluster_id', 'sample_id', 'group_id', 'sizeFactor', 'cluster_hi', 'cluster_lo'
    var: 'ENSEMBL', 'SYMBOL', 'gene_id', 'bio'
    uns: 'X_name'
    obsm: 'HARMONY', 'PCA', 'TSNE', 'UMAP'
    layers: 'logcounts'

In [4]:
# cell metadata file
cell_metadata = pd.read_csv("../../data/kang/01-pro/Kang18-cd.csv", index_col=0)
cell_metadata

,dat,cluster_id,sample_id,group_id,sizeFactor,cluster_hi,cluster_lo,PC1,PC2,PC3,...,PC41,PC42,PC43,PC44,PC45,PC46,PC47,PC48,PC49,PC50
1,Kang18,CD14+ Monocytes,1016,ctrl,1.968293,1,1,-9.601045,-7.751792,3.016167,...,0.099475,0.070150,0.214703,0.058486,0.437513,-0.191967,0.326641,-0.036196,1.284119,0.533591
2,Kang18,CD14+ Monocytes,1016,ctrl,0.744250,1,1,-9.054521,-7.939345,2.522054,...,1.182439,-0.079919,0.262830,-0.814220,-0.566263,-2.027848,0.595721,1.347794,-0.279134,0.059945
3,Kang18,CD14+ Monocytes,1015,ctrl,1.029569,1,1,-11.855952,-7.212761,0.041987,...,-0.631758,-0.201482,1.156170,1.111186,-0.525191,0.315115,-0.335878,0.021967,-0.471188,-0.312560
4,Kang18,NK cells,1015,ctrl,0.444801,2,1,2.747314,-0.531208,-7.456574,...,-0.435929,-0.544056,0.422136,1.457515,0.568264,-0.853002,-0.472918,-0.129515,-0.447437,-0.522960
5,Kang18,CD4 T cells,1016,ctrl,0.499307,3,1,0.619183,-1.797955,-2.663480,...,0.536027,0.306520,-2.136738,0.453564,0.138082,-2.098362,0.338719,-1.333443,-0.505534,-1.175635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12512,Kang18,CD14+ Monocytes,1244,stim,3.648575,16,1,-14.478118,6.542185,3.095319,...,-0.888261,-0.384828,-0.538036,-0.439191,-0.537528,0.236914,0.414060,0.113925,0.537911,-0.794013
12513,Kang18,CD4 T cells,1488,stim,0.882199,14,1,5.997583,1.688624,1.430163,...,0.473841,0.092925,-0.573882,-0.017628,0.390316,-0.613733,0.271678,0.270021,-0.147413,1.060443
12514,Kang18,CD4 T cells,1244,stim,0.652733,14,1,5.129642,3.206149,1.687573,...,0.491438,0.153523,0.174424,-1.145775,0.978448,0.817337,-0.603462,0.182335,0.862666,0.604474
12515,Kang18,B cells,1256,stim,1.351897,15,1,3.250699,-0.498331,2.144655,...,0.262880,-1.083421,-0.207687,-0.852032,0.259142,1.767377,-0.618935,0.571602,0.258167,-0.674563
12516,Kang18,CD4 T cells,1488,stim,0.735502,17,1,7.279697,1.338077,2.426364,...,0.736309,-0.511659,0.779633,1.213431,0.243969,-0.771976,0.423280,-0.166261,0.651672,-0.541006

In [5]:
# gene metadata file
gene_metadata = pd.read_csv("../../data/kang/01-pro/Kang18-rd.csv", index_col=0)
gene_metadata

             dat          ENSEMBL    SYMBOL   gene_id       bio
NOC2L     Kang18  ENSG00000188976     NOC2L     NOC2L  0.006046
HES4      Kang18  ENSG00000188290      HES4      HES4  0.017496
ISG15     Kang18  ENSG00000187608     ISG15     ISG15  0.233506
TNFRSF18  Kang18  ENSG00000186891  TNFRSF18  TNFRSF18  0.024728
TNFRSF4   Kang18  ENSG00000186827   TNFRSF4   TNFRSF4  0.019077
...          ...              ...       ...       ...       ...
PTTG1IP   Kang18  ENSG00000183255   PTTG1IP   PTTG1IP -0.006301
ITGB2     Kang18  ENSG00000160255     ITGB2     ITGB2 -0.004820
FAM207A   Kang18  ENSG00000160256   FAM207A   FAM207A  0.002081
S100B     Kang18  ENSG00000160307     S100B     S100B  0.002524
PRMT2     Kang18  ENSG00000160310     PRMT2     PRMT2  0.005346

[4180 rows x 5 columns]